name: McPlugin
version: '${project.version}'
main: com.github.patrickfrom.mcplugin.mcplugin.McPlugin
api-version: 1.17
authors: [ Patrick, Noah ]
commands:
  info:
    description: Info about the plugin
    usage: /<command>